-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
-- Creates prompts and responses tables

create table if not exists prompts (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz default now() not null
);

create table if not exists responses (
  id bigint generated by default as identity primary key,
  prompt_id bigint not null references prompts(id) on delete cascade,
  text text not null,
  created_at timestamptz default now() not null,
  embedding text
);

create index if not exists idx_responses_prompt_id on responses(prompt_id);
